# Generated by Django 4.1.4 on 2022-12-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ("-completed", "cart")},
        ),
    ]
