# Generated by Django 4.1.4 on 2022-12-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_orderitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ("completed", "cart")},
        ),
    ]
