# Generated by Django 4.1.4 on 2022-12-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_items_alter_order_ref_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
