# Generated by Django 4.1.4 on 2022-12-22 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0003_alter_orderitem_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("user", "item")},
        ),
    ]
